name: ci

on:
  - push
  - pull_request

permissions:
  actions: write
  contents: read

jobs:
  test:
    name: test

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: run tests
        run: cargo test --all-features --all-targets

  test-docs:
    name: test docs

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: run doc tests
        run: cargo test --doc --all-features

  check:
    name: check

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: install rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: check code
        run: cargo clippy --all-targets -- -D warnings

  check-docs:
    name: check docs

    runs-on: ubuntu-latest

    env:
      RUSTDOCFLAGS: -D warnings

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: install rust
        uses: dtolnay/rust-toolchain@nightly

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: install cargo-docs-rs
        uses: dtolnay/install@cargo-docs-rs

      - name: run cargo docs-rs
        run: cargo docs-rs --locked

  check-nix:
    name: check nix
    uses: ./.github/workflows/nix-check.yaml
    with:
      check: flake
    permissions:
      actions: write
      contents: read

  check-home-manager:
    name: check home manager
    uses: ./.github/workflows/nix-check.yaml
    with:
      check: home-manager
    permissions:
      actions: write
      contents: read

  check-format:
    name: check format
    uses: ./.github/workflows/nix-check.yaml
    with:
      check: format
    permissions:
      actions: write
      contents: read
